var CONFIG_EOL = {
  "cache": false,
  "version": 201907102109,
  "expire_data": {
    "default": 7200,
    "api/news/lists": 120
  },
"shouAI":false,
  "is_show_cache_size": false,
  "api_cache_time": 2592000,
  "api_cache_refresh_time": 20,
  "api_url_refresh_time": 20,
  "access_token": false,
  "chooseschool_limit_center": true,
   "chooseschool_limit_coop": {
     "qqbrowser": false,
    "bdbk": true,
    "bdkp": true,
    "bdwk": false,
    "jrtt": false,
    "qihujy": true,
    "qihukp": true,
    "shenma": true,
    "sougou": true,
    "wifi": true,
    "xiaomi": false,
    "youdao":false,
    "jingdong":false,
    "selfjrtt":false,
 "weixin":false,
   "xxqg":false,
"sdx":false,
"sdxapp":false,
  },
 "back_school": {
     "qqbrowser": false,
    "bdbk": false,
    "bdkp": false,
    "bdwk": false,
    "jrtt": false,
    "qihujy": false,
    "qihukp": false,
    "shenma": true,
    "sougou": true,
    "wifi": false,
    "xiaomi": false,
    "youdao":false,
    "jingdong":true,
    "selfjrtt":false,
    "weixin":false,
    "xxqg":false,
    "sdx":false,
    "sdxapp":false,
  },
  "download_limit_coop": {
    "qqbrowser": false,
    "bdbk": false,
    "bdkp": false,
    "bdwk": false,
    "jrtt": false,
    "qihujy": false,
    "qihukp": false,
    "shenma": true,
    "sougou": true,
    "wifi": false,
    "xiaomi": false,
    "jingdong": false,
    "selfjrtt":true,
    "weixin":true,
    "xxqg":true,
    "youdao":true,
    "sdx":true,
    "sdxapp":true,
    "txxw": false,
    "chinamo": true,
   "bdxcx": true,
"zsgkapp": true,
  },
  "showA": {
    "qqbrowser": true,
    "bdbk": true,
    "bdkp": true,
    "bdwk": true,
    "jrtt": true,
    "qihujy": true,
    "qihukp": true,
    "shenma": true,
    "sougou": true,
    "wifi": true,
    "xiaomi": true,
    "jingdong": true,
    "selfjrtt":false,
    "weixin":true,
    "xxqg":false,
    "youdao":false,
    "sdx":false,
    "sdxapp":false,
    "txxw": true,
    "chinamo":false,
  },
"showB": {
    "qqbrowser": true,
    "bdbk": true,
    "bdkp": true,
    "bdwk": true,
    "jrtt": true,
    "qihujy": true,
    "qihukp": true,
    "shenma": true,
    "sougou": true,
    "wifi": true,
    "xiaomi": true,
    "jingdong": true,
    "selfjrtt":false,
    "weixin":false,
    "xxqg":false,
    "youdao":false,
    "sdx":false,
    "sdxapp":false,
    "txxw": true,
    "chinamo":false,
  },
"showC": {
    "qqbrowser": true,
    "bdbk": true,
    "bdkp": true,
    "bdwk": true,
    "jrtt": true,
    "qihujy": true,
    "qihukp": true,
    "shenma": true,
    "sougou": true,
    "wifi": true,
    "xiaomi": true,
    "jingdong": true,
    "selfjrtt":false,
    "weixin":false,
    "xxqg":false,
    "youdao":false,
    "sdx":false,
    "sdxapp":false,
    "txxw": true,
    "chinamo":false,
  },
  "school_api_json": {
    'history_score': false,
    'special_score': false,
    'students_plan': false,
    'isExactConfig':true,
    'filing_line': false
  },
  "api_cache_api": [
    'apigkcx/api/video/lists',
    'apigkcx/api/news/lists',
    'apigkcx/api/special/SpecialSchoolLists',
    'apigkcx/api/school/hotlists',
    'apigkcx/api/school/gufenlists',
    'apigkcx/api/school/totallists',
    'apidata/api/gk/special/lists',
    'apidata/api/data/school/lists',
    'apidata/api/gk/special/salary',
    'apidata/api/gk/score/proprovince',
    'apidata/api/gk/school/scoresort',
    'apidata/api/gk/schoolSpecial/elective',
    'apidata/api/gk/plan/special'
  ],
  "api_secert_api": [
    'apidata/api/gk/special/salary',
    'apidata/api/gk/zytb/school',
    'apidata/api/gk/zytb/special',
    'apidata/api/gk/score/special',
    'apidata/api/gk/score/province',
    'apidata/api/gk/plan/special',
'apigkcx/api/user/sendcode',
  ],
  "api_config": {
  },
  "expire_path": [
  ] ,
"news_num": true,
"isLogin" :true,
  "isShowRecruit":true,
"mourning":false,
"chooseSchoolAlert":true,
benUp:10,
benDown:30,
zhuanUp:50,
zhuanDown:50,
"choose":2024,
"school_list":2024,
"activity_time":"2026年02月10日至02月25日",
is_coupon_popup: true,
activate_handle_nums: 2,
is_school_vip_activate: true,
chatFillsFlag:true,
voluntAssistantSwitch: true
}